name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'  # Set to your Python version

    - name: Clear Python cache
      run: |
        echo "Clearing Python pip cache"
        rm -rf ~/.cache/pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12  # Ensure you use the latest version
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: false
        heroku_config_vars: |
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          EMBEDDINGS_API_URL=${{ secrets.EMBEDDINGS_API_URL }}
          EMBEDDINGS_API_KEY=${{ secrets.EMBEDDINGS_API_KEY }}